### ISSUE TITLE
Sample code in README.md out of date

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [balliegojr/simple-dns#1]
Just an FYI - if I find time I will send a PR.

one ex. `ServiceDiscovery::new("_mysrv._tcp.local", 60, true)` now only takes 2 parameters.

**Comment by andrewdavidmackenzie** [comment]
Also, the dns responder one has a dependency on simple-dns that is not mentioned.

**Comment by balliegojr** [comment]
@andrewdavidmackenzie thanks, I've forgot to update the README, I will try to update it in the next few days
