### ISSUE TITLE
Panic (likely when something is odd with a frame)

### ISSUE THREAD

**Issue by zhiburt** [balliegojr/simple-dns#12]
Hi @balliegojr 

Just encounter it accidentally.
I tend to believe it should return a Error but don't panic in any case?

Sadly I can't provide a reproducible.

```
thread 'main' panicked at 'range end index 12 out of range for slice of length 10', /home/maxim/.cargo/registry/src/github.com-1ecc6299db9ec823/simple-dns-0.5.0/src/dns/packet.rs:108:41
```

Take care.

**Comment by balliegojr** [comment]
Hi @zhiburt 

Thanks for reporting this.

**Comment by balliegojr** [comment]
[This commit](https://github.com/balliegojr/simple-dns/commit/32dde38976fdb107dcf65aa63639692de32f35b8) should fix the issue
