### ISSUE TITLE
How do I get the domain name from the CNAME struct?

### ISSUE THREAD

**Issue by DonSheddow** [balliegojr/simple-dns#13]
Other enum variants like [A](https://docs.rs/simple-dns/0.5.1/simple_dns/rdata/struct.A.html) and [AAAA](https://docs.rs/simple-dns/0.5.1/simple_dns/rdata/struct.AAAA.html) have the `address` field, but there doesn't seem to be any way to get the contents of a [CNAME](https://docs.rs/simple-dns/0.5.1/simple_dns/rdata/struct.CNAME.html). Am I missing something?

**Comment by balliegojr** [comment]
Hello,

Sorry for taking this long to answer, I had a very busy week.
The CNAME is a wrapper for the Name, but it is missing a way to access the inner value, I will fix this and publish a new version, thanks for reporting this

**Comment by balliegojr** [comment]
Just published a fix for this, please let me know if it solves your use case

**Comment by DonSheddow** [comment]
Thanks for the quick fix! I'll mark this as resolved
