### ISSUE TITLE
upgrading bitflags from 1.3 to 2.4 breaks existing code

### ISSUE THREAD

**Issue by berlin-with0ut-return** [balliegojr/simple-dns#19]
hi, me again. i noticed that as part of the 0.5.4 release, the bitflags library was updated. the main breaking change with this update is that the Debug, Copy, Clone, Hash, PartialEq, and Eq traits are no longer automatically derived (see [this issue](https://github.com/bitflags/bitflags/issues/310) ). 
our existing code assumes the `Clone, Debug, PartialEq, Copy` traits for the `PacketFlag` struct in order to function. 

i went ahead and added this as a pull request - let me know if you anticipate any downstream issues with this change.

**Comment by balliegojr** [comment]
Hi, 

Sorry, I really missed that change when updating the dependencies.

Just published a new version with your fix
