### ISSUE TITLE
Long text doesn't work in Packet::parse and other stuff

### ISSUE THREAD

**Issue by Nuhvi** [balliegojr/simple-dns#25]
1. Long text doesn't work in Packet::parse
2. From Hashmap doesn't add `;` so it all considered one value.

I will open a PR adding a unit test and maybe even fix later. But in the meantime, just an issue to remember.

**Comment by balliegojr** [comment]
The TryFrom<String> implementation had a bug, it was adding 1 character more than it should, already fixed this on master
