### ISSUE TITLE
unable to get instance name in instance information

### ISSUE THREAD

**Issue by dvc94ch** [balliegojr/simple-dns#26]

**Comment by balliegojr** [comment]
I am thinking about changing the `get_known_services` to return a `HashMap<String, InstanceInformation>`, where the key would be the instance name, would that solve the issue?

```rust
    pub fn get_known_services(&self) -> HashMap<String, InstanceInformation> {
```

**Comment by dvc94ch** [comment]
That would be great. But even more I'd prefer to get a stream of discovered services and cache them myself.

**Comment by balliegojr** [comment]
Hi, I've made a few changes in this [commit](https://github.com/balliegojr/simple-dns/commit/b4db19125a700203f666872253a5fc116b6cfc2b) to add a notification channel.

the TL;DR; of the change is the one bellow (the async version uses a tokio channel)
```rust
pub fn new_with_scope(
        instance_name: &str,
        service_name: &str,
        resource_ttl: u32,
        on_discovery: Option<std::sync::mpsc::Sender<(String, InstanceInformation)>>,
        network_scope: NetworkScope,
    ) -> Result<Self, SimpleMdnsError>
```

Please let me know if this will solve your use case

**Comment by dvc94ch** [comment]
works great! thanks!
