### ISSUE TITLE
A BUG in opt_mut()

### ISSUE THREAD

**Issue by reflyable** [balliegojr/simple-dns#35]
NAME in EDNS0 RR should be 0，but now it is “.” in packet generated with opt_mut. 

![image](https://github.com/user-attachments/assets/35235536-eb6e-423e-8a10-a61c6b232458)

![image](https://github.com/user-attachments/assets/7f160280-d0fe-4230-bcb9-c729dd68479d)

This is because 
```
crate::Name::new_unchecked("."),
```
in Header.opt_rr()

![image](https://github.com/user-attachments/assets/2561f6e2-ca73-4e82-af34-9ae56bd1813e)

**Comment by reflyable** [comment]
I'm not entirely sure if Name::new_unchecked should handle "." in this way, but EDNS records indeed should have a name with the content b'\x00'.

**Comment by balliegojr** [comment]
@reflyable thanks for reporting this, I will take a look as soon as I have time

**Comment by balliegojr** [comment]
@reflyable the main branch should have a fix for this now, are you able to verify with that branch?

**Comment by reflyable** [comment]
It now works well in my code. Thanks for your fix.

**Comment by balliegojr** [comment]
I have release a new version (0.9.0) with the fix
