### ISSUE TITLE
Relax `is_valid_label` to accept lablels starting with digits

### ISSUE THREAD

**Issue by Nuhvi** [balliegojr/simple-dns#38]
v0.9.0 (04bd1f4) breaks `pkarr` crate because Pkarr uses z-base32 encoded public keys as TLDs, and these often starts with a digit.

After a quick research, it appears that [this restriction has been relaxed](https://serverfault.com/questions/638260/is-it-valid-for-a-hostname-to-start-with-a-digit) a long time ago, and in fact you can check on Namecheap, where a domain starting with a number can be purchased just fine.

**Comment by balliegojr** [comment]
:man_facepalming: Thanks for reporting this. Version 0.9.1 has this fixed.
