### ISSUE TITLE
Add support for EDNS

### ISSUE THREAD

**Issue by owocean** [balliegojr/simple-dns#5]
Title.   
No, I'm not talking about that stupid Ethereum DNS, I'm talking about [this](https://en.wikipedia.org/wiki/Extension_Mechanisms_for_DNS)  

Using `dig` to test a simple lookup, I'm have to pass the `+noedns` parameter otherwise I get `Err(InvalidClass(4096))` when trying to `Packet::parse`  
I'm worried this will cause compatibility issues, as I fear that client resolvers will attempt to use edns exclusively like `dig` does

**Comment by balliegojr** [comment]
Yes, it is in my plans to implement all (or at least most) of  RFCs related to DNS, this will take a little bit of time tough....

**Comment by balliegojr** [comment]
Latest version (0.5.0) on main should have this solved now
